# Generated by Django 3.0.7 on 2020-12-31 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppw', models.CharField(max_length=20)),
                ('pn', models.CharField(max_length=20)),
                ('mi', models.CharField(max_length=20)),
                ('appw', models.CharField(max_length=20)),
                ('result', models.CharField(max_length=50)),
            ],
        ),
    ]
